### ISSUE TITLE
D드라이브에 있는 프로젝트파일로(.docp) 열었을 경우 랜더링이 되지 않습니다.

### ISSUE THREAD

**Issue by mnutube-jmw** [mnutube/downcap-client#9]
electron-starter:821 에서 문제 발생

ass 파일 정상 생성 : 프로그램 설치 위치의 temp폴더에 생성 (일반적으로 C드라이브)
assfilePath를 절대경로에서 상대경로로 만들어주는 과정에서 클라이언트를 D드라이브의 프로젝트 파일로 열면 현재 프로그램 실행위치가 프로젝트 파일위치(D:\)로 나오게 되어 C드라이브 위치한 ass파일과 비교해 상대경로로 만드는 과정에서 절대경로가 그대로 유지되어버립니다. 
이후 랜더링 절대경로 사용한 랜더링시 실패합니다.

`      FFmpeg starting conversion with command: ffmpeg -i D:\무한도전 무야호_360p.mp4 -y -b:v 4000k -vf ass=temp/subtitle.ass:shaping=complex D:\1212121212122122222.mp4

fail: Electron.FFmpegHelper
      {}`

**Comment by mnutube-new** [comment]
https://github.com/mnutube/downcap-client/commit/b7099f0133372e9520272114f75d8f18a6d38538 커밋으로  수정 완료 했습니다.
